repos:
  - repo: local
    hooks:
      - id: nbstripout
        name: Strip Jupyter notebook outputs
        entry: nbstripout
        language: python
        additional_dependencies:
          - nbstripout>=0.8.1
        files: \.ipynb$
